/*============== practica 1 ================
programaciòn orientada a objetos 2027-1

Villalobos Estrada Osvaldo Yafte  Equipo 1
Cuenta: 322024443
============================================*/
public class Division{
    public static void main(String[] arg){
    //===declaracion de variables====
        int a = 455; // variable a xd
        int b = 10; // se declara la variable b
        
        //se construye la operacion 
       float resultado = (float) a / b; //se declara la operacion y se guarda en resultado

        // se imprime el resultado
        System.out.println("El resultado es:"+resultado);
    }
    
}