/* Practica 1 Programación orientada en objetos 2027-1 */
/* Melgarejo Cervantes Manuel Alejandro*/ 
/* Equipo : 1 */
/* Número de cuenta: 322063132*/
/* Creamos una clase publica de multiplicar (recordar, la clase tiene que tener el mismo nombre que el archivo) */
public class multiplicar{
  /* Declaramos la linea que según investigue, es para que el programa se ejecute lo que estara dentro del código */ 
  public static void main (String[] args) {
    /* Declaramos Variables para empezar*/ 
    int numero1 = 5;
    int numero2 = 6;
    /* Una vez declarando las variables asi que haremos la siguiente operación */ 
    in resultado = numero1 * numero2; 
    /* Una vez declarado y haciendo la operación haremos que el codigo haga la impresión de la operación */ 
    System.out.printl (" El resultado es: " + resultado); 
  }
}