/*==========Práctica 1==========
Programación Orientada a Objetos 2027-1

Landeros López Victor Manuel.    Equipo 1
No:3-16229849

=============================*/

public class Suma {
    public static void main(String[] args) {

        // ==Declaración y definición de variables==
        int a = 15; //Primer valor 
        int b = 27; // Segundo valor 
        int resultado = 0; //Variable para almacenar la suma 

        // ==Operación suma==
        resultado = a + b; //Asignación de la suma a resultado  

        // ===Impresión en pantalla===
        System.out.println("La suma de " + a + " + " + b + " es igual a: " + resultado);
    }
}
